version: '3'

services:
  web:
    container_name: rails_api_app_web
    build:
      context: ./
      dockerfile: docker/ruby/Dockerfile
    command: pumactl -F config/puma.rb start
    volumes:
      - ./www:/var/www
    links:
      - database
    environment:
      TZ: Asia/Tokyo
      RAILS_MASTER_KEY:

  nginx:
    container_name: rails_api_app_nginx
    image: nginx:latest
    ports:
      - 81:80
    volumes:
      - ./www/public:/var/www/public
      - ./www/tmp:/var/www/tmp
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    environment:
      TZ: Asia/Tokyo

  database:
    container_name: rails_api_app_pgsqld
    image: postgres:latest
    ports:
      - "54321:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rails_api
      POSTGRES_USER: rails_api_user
      POSTGRES_PASSWORD: secret

#  redis:
#    container_name: rails_api_app_redis
#    image: redis:latest
#    command: redis-server --appendonly yes --requirepass secret
#    environment:
#      TZ: Asia/Tokyo

volumes:
  pgsql_data:
    driver: local